version: '3.8'

services:
  order-service:
    build: .
    container_name: order-service-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=subscriptions
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - PRODUCT_SERVICE_URL=http://product-service:3001
    networks:
      - order-network
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: order-postgres-dev
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5433:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - order-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d subscriptions"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  order_postgres_data:

networks:
  order-network:
    driver: bridge